language: node_js
node_js:
  - node
install:
  - npm install
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - npm run test
after_success:
  - npm run coveralls 

