language: node_js
node_js:
  - node
before_install:
  - psql -c 'create database travis_ci_test;' -U postgres
install:
  - npm install
cache:
  directories:
    - "node_modules"
before_script:
  - cross-env NODE_ENV=test ./node_modules/.bin/babel-node tables.js createAllTables
script:
  - npm run test
after_success:
  - npm run coveralls 

